### PR TITLE
Added integration test for going to settings

### LINKED ISSUE #183: Add integration test for going to settings
An integration test that ensures that you can go to settings from the startpage. It should live in a new file `App.test.tsx`
```jsx
it("should allow you to go to settings", () => {
  render(<App />);
  /* 1. code to expand the list in the sidebar and click on the settings link */
  /* 2. assert that you are on the settings page, by e.g. checking the presence of some text */
});
```

### PR DESCRIPTION
**Pull request by mchiesa**
closes #183

### CODE REVIEW

**Comment by MoSattler** [comment]
@limbovski no, always test from the perspective of the user. 
URLs can change without the UX changing. Realying on the url would mean we have a broken test while the actual ap would still be working. That'd make the test susceptible to false positives, what we want to avoid.

**Comment by limbovski** [comment]
> @limbovski no, always test from the perspective of the user.
> URLs can change without the UX changing. Realying on the url would mean we have a broken test while the actual ap would still be working. That'd make the test susceptible to false positives, what we want to avoid.

Super stuff that makes a lot of sense Mo.

So typically we would need something a little more unique than "Profile and Settings" as there could be other pages with that text at some stage? Unless we tested the H1 tag for that text?

**Comment by mchiesa** [comment]
> 100%.
> 
> Just a question for @MoSattler or @mchiesa would you expect in a more robust application to test for the URL of the resulting page - window.location.href etc?

Not really sure, I'm also not sure about the text "Profile and Settings" that the test is checking. 

> @limbovski no, always test from the perspective of the user.
> URLs can change without the UX changing. Realying on the url would mean we have a broken test while the actual ap would still be working. That'd make the test susceptible to false positives, what we want to avoid.

Nice to know. I also had a similar question. Right now we need a "Profile and Settings" text and that text will be removed when we actually create the settings screen so we will need to update the test as well. Is that ok?

**Comment by MoSattler** [comment]
@limbovski yes, you are right. There are some tools an strategies to make it more unique. E.g. [`within`](https://testing-library.com/docs/dom-testing-library/api-helpers#within-and-getqueriesforelement-apis) let's you specify something like
> Make sure that inside this area of the app is a text
For these scenarios it helps a bunch to have semantic identifiers, like roles. 
But perfect is the enemy of good, so always look what's doable with a reasonable amount of work, and in most cases just checking for text works fine.

@mchiesa that is ok! Because we're testing on the `App` level right now, meaning this is a top-level integration test, we might need to change the tests if part of the app change.

**Pull request merged**
