### PR TITLE
Fix styling UserCard

### LINKED ISSUE #91: Some UserCard style improvements
1. reduce the size from [`50`](https://github.com/HandsOnLearning/the-project/blob/master/src/components/Sidebar/components/UserCard/styles.js#L45-L46) to 42px

2. The Name in `TextContainer` should align to the top, the email address to the bottom. This can be done by some flex changes in `TextContainer` and `LeftContent`

### PR DESCRIPTION
**Pull request by SimonNord**
fixes #91

### CODE REVIEW

**Comment by SimonNord** [comment]
Having some issue with the alignment of the text,
Been trying to apply position: space-between in TextContainer but now it seems that the height of the TextContainer is not as high as the image, thought this was automatic with flexbox.

Can you give me some tips on how to fix this?

**Comment by limbovski** [comment]
This might help @SimonNord 

`display: flex;
  flex-direction: column;
  justify-content: space-between;`

**Comment by SimonNord** [comment]
Almost sure I’ve tried that :) gonna take a look at it again later. Thanks for tips

**Comment by limbovski** [comment]
> @limbovski Almost sure I’ve tried that :) gonna take a look at it again later. Thanks for tips

No hassle @SimonNord, on closer look you'll also need to remove the alignment properties from the parent element: 

```-webkit-align-items: center;
-webkit-box-align: center;
-ms-flex-align: center;
align-items: center;
```

**Comment by SimonNord** [comment]
Thanks @limbovski ! worked =) need to read up some more about Flexbox, didnt know that the parents flex options did affect the item/child.

**Comment by limbovski** [comment]
@SimonNord in order for me to review this should I pull down the branch and test as previously I just seen it in the master. What's the standard procedure?

**Pull request merged**
