### PR TITLE
Fixes margin on UserCard ExpandedList

### LINKED ISSUE #165: UserCard ExpandedList is too wide.

### PR DESCRIPTION
**Pull request by limbovski**
closes #165

### CODE REVIEW

**Comment by limbovski** [comment]
> Lookgs good, though I am wondering if we could use `<Spacer />` here.

As in put a spacer either side of the component to create the margin?

**Comment by MoSattler** [comment]
@limbovski once this is merged, you should be able to wrap it inside a `Spacer` like this
```jsx
<Spacer left={x} right={y}>
  {/*content*/}
</Spacer>
```

**Comment by limbovski** [comment]
> @limbovski once this is merged, you should be able to wrap it inside a `Spacer` like this
> 
> ```js-jsx
> <Spacer left={x} right={y}>
>   {/*content*/}
> </Spacer>
> ```

Question,  the Spacer padding parameters multiply by 8 and this margin requires 10... ?

**Comment by MoSattler** [comment]
@limbovski make it 8 for now.

**Pull request merged**
