### PR TITLE
Refactors Sidebar

### PR DESCRIPTION
**Pull request by limbovski**
Issues #190 
Rename all occurences of SideBar to Sidebar
Tidies up Sidebar code to lay the foundation for Menu and MenuItem instead of SidebarItem

### CODE REVIEW

**Comment by SimonNord** [comment]
This one is kinda related to #172, Im pausing that one and wait for this PR to be merged. 
This so I can use the Menu and MenuItem there too.

**Comment by MoSattler** [comment]
Looks like you broke the tests

**Comment by limbovski** [comment]
> Looks like you broke the tests

Along with my head 😂 I will fix tomorrow.

**Comment by limbovski** [comment]
Pasting this here as a record...

So tests pass. To explain the issue and solution in case anyone else ever gets it... I'm on a mac and was working on an issue to Refactor the sidebar and part of it which I thought was trivial was to rename all instances of SideBar to Sidebar. So it seems the best way to rename files that are in your project is to use git mv oldfile newfile which also works for folders and for moving. The issue was, I didn't know this before I added and committed and pushed, so while it was working on my machine, git didn't add any of the renamed files or folders to my commit, so it failed tests. Figuring this out took a long time and as it also happens Mac is case insensitive, so even when I realised actually renaming is not as simple as just running that command because Mac thinks you cannot rename MacBookPro -> macbookpro because they are the same. So I set a config variable as follows: git config core.ignorecase false and it didn't seem to work probably because I need to restart terminal or whatever and I ended up using git mv -f oldfile newfile to -f Force the change. That sorts the files out, but when it comes to folders the best way is as Mo explained above. Rename it to a temp name, git add, git commit, then rename the temp name to the desired newname... Fun times! Took a few hours that one


Also, no issues if this ends up being a dead duck even after all that effort, I learned a lot there.

**Comment by MoSattler** [comment]
Same as [here](https://github.com/HandsOnLearning/the-project/pull/194#pullrequestreview-416041067). 
You should probably add the tests here, and once this is merged, rebase #194, which automatically should be fine then.

**Pull request merged**
